services:
  postgres:
    image: postgres:17.6-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - application-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME} -h 127.0.0.1 || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 12
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy

  # Uncomment to use redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - 6379:6379

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - filesystem:/usr/src/app/files
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  filesystem:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./files
  application-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./postgres-data
